### ISSUE TITLE
Not detecting causality on well-known datasets?

### ISSUE THREAD

**Issue by timothyjgraham** [DarkEyes/VLTimeSeriesCausality#2]
Hi there,

To get a better sense of VLTimeSeriesCausality, I ran it on the well-known "chicken and egg" dataset from the `lmtest` package.

However, it is unable to detect causality, as it returns a false value when it should return positive.

Here is the code to reproduce the issue. Could you please clarify? I really like this method and software, but I am concerned about issues of validity, and would like to seek your clarification.

```
# chicken and egg causality test using standard Granger and a well-known dataset
library(lmtest)
data(ChickEgg)
# chickens granger-cause eggs?
grangertest(egg ~ chicken, order = 3, data = ChickEgg) # cannot reject the null hypothesis
# eggs granger-cause chickens?
grangertest(chicken ~ egg, order = 3, data = ChickEgg) # we reject the null hypothesis

# chicken and egg causality test using VLTimeCausality
data(ChickEgg)
ChickEgg <- as.data.frame(ChickEgg)
out_test1 <- VLTimeCausality::VLGrangerFunc(X=ChickEgg$egg,Y=ChickEgg$chicken)
out_test1$BICDiffRatio
out_test1$XgCsY  # false
out_test2 <- VLTimeCausality::VLGrangerFunc(X=ChickEgg$chicken,Y=ChickEgg$egg)
out_test2$BICDiffRatio
out_test2$XgCsY  # false
```

**Comment by DarkEyes** [comment]
Hi,

Thanks for raising this issue. In our  VL-Granger, there are several decision criteria for determining whether X causes Y along with the variable-lag test. Our default option is the BIC difference ratio, which can only detect the strong signal of causation.  We also have the f-test of BIC as a decision criterion for users to choose. If we want to compare the normal Granger test with the VL-Granger test using the same decision criterion, we typically use f-test option in both test. For the ChickEgg data, below are the results of VL-Granger using f-test.

> library(lmtest)
> data(ChickEgg)
> ChickEgg <- as.data.frame(ChickEgg)
> out_test1 <- VLTimeCausality::VLGrangerFunc(X=ChickEgg$egg,Y=ChickEgg$chicken)
>out_test1$XgCsY_ftest
[1] TRUE
>out_test1$p.val
[1] 0.004980847
>out_test2 <- VLTimeCausality::VLGrangerFunc(X=ChickEgg$chicken,Y=ChickEgg$egg)
>out_test2$XgCsY_ftest
[1] FALSE
> out_test2$p.val
[1] 1

**Comment by timothyjgraham** [comment]
Hi Chainarong, thanks for the reply - I am very glad to see that there is an option for the f-test (sorry that I somehow missed this in the documentation!). I look forward to applying this model and citing your work :-). Tim
