### ISSUE TITLE
Question about BIC difference ratio versus f-test of BIC

### ISSUE THREAD

**Issue by timothyjgraham** [DarkEyes/VLTimeSeriesCausality#3]
This is a wonderful package - thank you for the contribution.

I have a question about the `VLGrangerFunc()` function.

Suppose that I run this on a time series pair `X` and `Y`, with the result that the `XgCsY` is false while the `XgCsY_ftest` is true. 

Can you please explain what this means? I interpret it as `X` 'weakly causes' `Y`, as opposed to strong causality for the BIC ratio.

Any clarifications much appreciated.

**Comment by DarkEyes** [comment]
Thank you for being interested in our package. In your case, yes, X 'weakly causes' Y. 

We have a result in [1] Table 4 column 1 about BIC difference ratio vs. F-test. The result shows  that VL-Granger with BIC difference ratio failed to detect causal relations but VL-Granger with F-test successfully detect the relations for two real-world datasets: Gas furnace and Old faithful geyser. So, according to the empirical result, we interpret that F-test can detect some weak causal relations , while BIC difference ratio cannot detect them. Mostly, if  BIC difference ratio finds a causal relation, then F-test typically finds it too; at least, for our results from both simulation and real-world datasets. However, the another way around is not true. 

All results have been peer reviewed and the draft at [1] will be published soon at [2].

[1] https://arxiv.org/abs/2002.00208
[2] Chainarong Amornbunchornvej, Elena Zheleva, and Tanya Berger-Wolf (2021). Variable-lag Granger Causality and Transfer Entropy for Time Series Analysis. ACM Transactions on Knowledge Discovery from Data (TKDD), 15(y), 1-30. https://doi.org/10.1145/3441452

**Comment by timothyjgraham** [comment]
Thanks @DarkEyes, I appreciate the reply.

This is very helpful information for my research. I am wondering if you can expand at all about two aspects:

1. Is it possible to measure the effect size for the F-test results?
2. Do you have any explanation for why BIC difference ratio can detect causal relations that F-test cannot detect? And how does this matter, for example with the gas furnace and Old Faithful geyser results in [1] Table 4, Column 1.

Thank you!

**Comment by DarkEyes** [comment]
For the first question, p-value only tells us whether there is a causal relation or not.   However, we have a way to measure the effect size as follows.

> # Generate simulation data
> TS <- VLTimeCausality::SimpleSimulationVLtimeseries() # ground truth: X causes Y
> out<-VLTimeCausality::VLGrangerFunc(Y=TS$Y,X=TS$X) 
> out$BIC_H1
[1] 0.09758236
> out$BIC_H0
[1] 0.7034139
> out$BIC_H0 - out$BIC_H1
[1] 0.6058316

In the above code, out$BIC_H0 - out$BIC_H1 compares the BIC at the null model (magnitude of regression residual of Y past predicts Y) vs. the alternative model (magnitude of regression residual of Y and X past predict Y). F-test uses out$BIC_H0 and out$BIC_H1 to compute its p-value. I think you can use out$BIC_H0 - out$BIC_H1 as a proxy for effect size. 

For the second question, we still do not have a theoretical explanation yet; we only have an empirical evidence.

**Comment by timothyjgraham** [comment]
Brilliant - thank you for the response. This helps me understand the model much better, including interpretation of results.

**Comment by timothyjgraham** [comment]
> For the first question, p-value only tells us whether there is a causal relation or not. However, we have a way to measure the effect size as follows.
> 
> > # Generate simulation data
> > TS <- VLTimeCausality::SimpleSimulationVLtimeseries() # ground truth: X causes Y
> > out<-VLTimeCausality::VLGrangerFunc(Y=TS$Y,X=TS$X)
> > out$BIC_H1
> > [1] 0.09758236
> > out$BIC_H0
> > [1] 0.7034139
> > out$BIC_H0 - out$BIC_H1
> > [1] 0.6058316
> 
> In the above code, out$BIC_H0 - out$BIC_H1 compares the BIC at the null model (magnitude of regression residual of Y past predicts Y) vs. the alternative model (magnitude of regression residual of Y and X past predict Y). F-test uses out$BIC_H0 and out$BIC_H1 to compute its p-value. I think you can use out$BIC_H0 - out$BIC_H1 as a proxy for effect size.
> 
> For the second question, we still do not have a theoretical explanation yet; we only have an empirical evidence.

@DarkEyes, I know that I've closed this issue, however I have one more quick question.

If the value of `out$BIC_H0 - out$BIC_H1` is negative, do we just take the absolute value? Unless I'm mistaken, it doesn't make sense statistically to have negative effect sizes, because there cannot be an inverse relationship here.

**Comment by DarkEyes** [comment]
For out$BIC_H0 - out$BIC_H1, there are three cases: positive, near zero and negative cases. 

The out$BIC_H0 represents the magnitude of error of the Y-past-predicts-Y model, while out$BIC_H1 represents the magnitude of error of the X & Y-past-predicts-Y model.

If out$BIC_H0 - out$BIC_H1 is positive, then it means that the alternative model performs really well with an effect size out$BIC_H0 - out$BIC_H1.

If out$BIC_H0 - out$BIC_H1 is near zero, then it means that the alternative model  and null model perform no difference with an effect size around zero.

However, if out$BIC_H0 - out$BIC_H1 is negative, then it means that the alternative model performs really bad even worse than the null model. Theoretically, it should not happen since the performance of regression of Y & X past on Y should at least the same as the performance of regression of Y past on Y. This is because   Y & X past is a larger model that subsumes the Y past model. However, an optimizer sometime makes some strange estimation and its can happen. I would treat  a negative  value of out$BIC_H0 - out$BIC_H1 as a non-effect case.

**Comment by timothyjgraham** [comment]
Hi @DarkEyes, once again thank you for the detailed reply - this is very helpful and I'm sure others will find it helpful too.

> Theoretically, it should not happen

This is what confused me as well, so I'm glad you can clarify why this happens due to the optimiser.
